on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: streak-counter
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_STREAK_COUNTER }}
          package: ./streak-counter/package.json
          access: public